import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by @ducanh2912/next-pwa at build time — not source.
    "public/sw.js",
    "public/swe-worker-*.js",
    "public/workbox-*.js",
    "public/worker-*.js",
    "public/fallback-*.js",
    "public/*.js.map",
    // Deno runtime (Supabase Edge Functions) — separate toolchain/lint.
    "supabase/functions/**",
  ]),
]);

export default eslintConfig;
